### ISSUE TITLE
Can this be run on Mac, can't see instructions for running.

### ISSUE THREAD

**Issue by KendallDoesCoding** [what-language/what-language.github.io#3]
Does What-Language work for Mac OS, can't see instructions to download.

**Comment by shourgamer2** [comment]
> Does What-Language work for Mac OS, can't see instructions to download.

Yes it can run. The Mac os runs of the linux kernel so the linux version of what language will work i think

**Comment by KendallDoesCoding** [comment]
> > Does What-Language work for Mac OS, can't see instructions to download.
> 
> Yes it can run. The Mac os runs of the linux kernel so the linux version of what language will work i think

Please run your tests and mention that in README in that case. (using a emulator (if there is one out there for free))

**Comment by shourgamer2** [comment]
> > > Does What-Language work for Mac OS, can't see instructions to download.
> > 
> > Yes it can run. The Mac os runs of the linux kernel so the linux version of what language will work i think
> 
> Please run your tests and mention that in README in that case. (using a emulator (if there is one out there for free))
Will edit the readme but there is no emulator for mac so we will ask some other ppl to test

**Comment by KendallDoesCoding** [comment]
*Ya bro, that works too.*
